lib/mhq_site_web/router.ex
defmodule MhqSiteWeb.Router do
  use MhqSiteWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MhqSiteWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/about", AboutController, :main
    get "/contact", ContactController, :main
  end

  # Other scopes may use custom stacks.
  # scope "/api", MhqSiteWeb do
  #   pipe_through :api
  # end
end

lib/mhq_site/application.ex
defmodule MhqSite.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      MhqSite.Repo,
      # Start the endpoint when the application starts
      MhqSiteWeb.Endpoint
      # Starts a worker by calling: MhqSite.Worker.start_link(arg)
      # {MhqSite.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: MhqSite.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    MhqSiteWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/mhq_site/repo.ex
defmodule MhqSite.Repo do
  use Ecto.Repo,
    otp_app: :mhq_site,
    adapter: Ecto.Adapters.Postgres
end

lib/mhq_site_web/controllers/about_controller.ex
defmodule MhqSiteWeb.AboutController do
  use MhqSiteWeb, :controller

  alias MhqSite.MHQ
  alias MhqSite.MHQ.About

  def main(conn, _params) do
    render(conn, "main.html")
  end

end

lib/mhq_site_web/controllers/contact_controller.ex
defmodule MhqSiteWeb.ContactController do
  use MhqSiteWeb, :controller

  # alias MhqSite.MHQ
  # alias MhqSite.MHQ.Contact

  def main(conn, _params) do
    render(conn, "main.html")
  end

end

lib/mhq_site_web/controllers/page_controller.ex
defmodule MhqSiteWeb.PageController do
  use MhqSiteWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/mhq_site_web/views/about_view.ex
defmodule MhqSiteWeb.AboutView do
  use MhqSiteWeb, :view
end

lib/mhq_site_web/views/contact_view.ex
defmodule MhqSiteWeb.ContactView do
  use MhqSiteWeb, :view
end

lib/mhq_site_web/views/error_view.ex
defmodule MhqSiteWeb.ErrorView do
  use MhqSiteWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/mhq_site_web/views/layout_view.ex
defmodule MhqSiteWeb.LayoutView do
  use MhqSiteWeb, :view
end

lib/mhq_site_web/views/page_view.ex
defmodule MhqSiteWeb.PageView do
  use MhqSiteWeb, :view
end

lib/mhq_site_web/templates/about/main.html.eex
<div class="main">
  <h1>About MHQ</h1>


  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis consequat turpis ut consectetur sollicitudin.
    Pellentesque mi dui, venenatis ut fringilla quis, consequat vel erat. Aliquam quis convallis felis. Mauris tempor
    eros
    ligula, pulvinar sagittis nulla vehicula eget. Sed facilisis tortor ac quam pharetra pretium. Aliquam sed lacus
    felis.
    Vestibulum at tristique justo. Aliquam erat volutpat. Pellentesque malesuada risus sed sem tincidunt posuere vitae
    suscipit mauris. Curabitur eu maximus lorem, ac feugiat lacus. Integer enim tellus, suscipit quis sollicitudin in,
    cursus a nisl. Maecenas ornare, est ut vehicula venenatis, neque ante ornare orci, at volutpat nulla augue ut
    lectus.
    Fusce aliquam aliquam purus et vulputate. Nunc rutrum rutrum orci eu congue.

    Curabitur a hendrerit tortor. Vivamus vitae nisi ut odio dignissim porta. Phasellus efficitur imperdiet odio, a
    viverra erat sagittis convallis. Aliquam nec nibh in nulla tempor condimentum. Duis bibendum posuere lectus, at
    cursus
    libero ultrices id. Proin at pulvinar ligula. Mauris quis velit auctor, semper lacus ac, ornare leo. Ut molestie
    maximus lacus, sed auctor sem rhoncus in. Quisque mollis accumsan faucibus. Maecenas congue aliquam justo, eu
    vehicula
    ipsum pretium ut. Proin nulla risus, convallis vitae rutrum et, venenatis vel turpis. Cras justo justo, pharetra sit
    amet lacinia a, pretium ac ex. Nullam et nisi faucibus, tempor orci id, pellentesque mauris. Aliquam erat volutpat.

    Vivamus tincidunt sapien non faucibus tempor. Sed aliquam aliquam dolor. Duis malesuada, massa sit amet viverra
    hendrerit, nisl arcu tincidunt eros, vitae auctor justo odio ut elit. Sed quis maximus velit. Donec mattis elementum
    ligula, nec mollis odio aliquet sit amet. In eget aliquet leo. Nunc posuere malesuada imperdiet. Maecenas eget risus
    placerat, aliquam leo et, pretium tellus. Curabitur maximus elit bibendum dapibus vulputate. Sed vel leo laoreet
    felis
    bibendum tincidunt a in est. Morbi tellus arcu, efficitur non elit ac, maximus hendrerit quam. Nunc vel mauris at
    tellus commodo tincidunt a sed lectus. Pellentesque malesuada tortor purus, eget sollicitudin nunc iaculis et.
  </p>
</div>

lib/mhq_site_web/templates/contact/main.html.eex
<div>
<h1>Contact Us!</h1>
</div>

<%# <ul id='msg-list' class='row' style='list-style: none; min-height:200px; padding: 10px;'></ul>

<div class="row">
  <div>
    <input type="text" id="name" class="form-control" placeholder="Your Name" autofocus>
  </div>
  <div>
    <input type="text" id="msg" class="form-control" placeholder="Your Message">
  </div>
</div> %>

   <div id="chat-box">
    </div>
    
    <form id="chat-form">
      <input type="text" placeholder="Username" id="user-name"></input>
      <textarea placeholder="Your comment" id="user-msg"></textarea>
      <button type="submit">Post</button>
    </form>

lib/mhq_site_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>MHQ Consulting</title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
</head>

<body>
  <div class="container">

    <div class="nav-wrapper">
      <img src="<%= Routes.static_path(@conn, "/images/logo.png") %>" alt="MHQ Logo" height="45" width="45" />
      <div class="topnav">
        <%= link "Home", to: Routes.page_path(@conn, :index) %>
        <%= link "About", to: Routes.about_path(@conn, :main) %>
        <%= link "Contact", to: Routes.contact_path(@conn, :main) %>
      </div>
    </div>

    <%= render @view_module, @view_template, assigns %>
  </div>
  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>

lib/mhq_site_web/templates/page/index.html.eex
<div class="main">
  <h1>MHQ Consulting</h1>
  <p>A Lucena City based IT development and consulting company.</p>
</div>